### ISSUE TITLE
PSF generated through on_the_fly True/False different

### ISSUE THREAD

**Issue by abhijithrajan** [spacetelescope/pandeia-coronagraphy#6]
Hello,

I noticed that the PSFs appear to have different morphology depending on whether you use the pre-computed version or the webbpsf version. I've attached a figure showing the difference.

<img width="995" alt="screen shot 2017-08-18 at 3 51 25 pm" src="https://user-images.githubusercontent.com/1957246/29475390-7d93f69e-842d-11e7-84f0-1c3433abc4c9.png">

All other parameters are kept consistent between the two calls.

**Comment by mperrin** [comment]
Things we just checked that didn't explain this: 
- WebbPSF version (ETC was using 0.6rc2 3 months ago and there haven't been major changes to 0.6 now)
- wavelength (I thought that maybe it was the ETC using precomputed PSFs at 10.60 and 10.835 microns, but that doesn't seem to make enough of a difference in some quick tests just now)
- sampling (I worried that since the ETC is using pixel/3 sampling it's an odd number instead of even so the FQPM cancellation is not as exact. but again this makes a small difference but nothing so abrupt as above.

**Comment by mperrin** [comment]
Aaaah, it's obvious if you read the PSF headers closely enough!

`CORONMSK= 'FQPM1140'           / Image plane mask  `

The "FQPM1065" PSFs were somehow generated with the 11.40 micron mask.

**Comment by abhijithrajan** [comment]
One of those times, you want to play the sarcastic slow-clap gifs.

**Comment by mperrin** [comment]
Hi @ariedel  - you'll want to see this one. @abhijithrajan has just found a problem with the existing PSF library for the MIRI FQPM1065 mode.  Good thing you just told me yesterday you're working on updating the PSF generation script. Here's something to add to the to-do list for that!

**Comment by ariedel** [comment]
Ha, I caught that mistake when going though the PSF generation for a different reason. I'll file a ticket and get that fixed.
